<a href="https://colab.research.google.com/github/HusanboyMuminov/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [7]:
import pandas as pd

In [8]:
print(pd.__version__)

2.2.2

In [9]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [10]:
df.head() # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [14]:
df.tail(-1) # default 5 rows

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [17]:
df.shape

(7, 2)

In [18]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [19]:
df.dtypes

cars      object
counts     int64
dtype: object

In [21]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [22]:
df.describe(include="all") # numerical columns only

       cars    counts
count     7  7.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.714286
std     NaN  3.199702
min     NaN  1.000000
25%     NaN  2.500000
50%     NaN  3.000000
75%     NaN  7.500000
max     NaN  9.000000

In [23]:
df.iloc[1:4]

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       8

In [24]:
df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [26]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [31]:
df[df["cars"] == "Tesla"] #counts > 3

    cars  counts
3  Tesla       8

In [32]:
# df.mean(numeric_only=True)
df["counts"].mean()

np.float64(4.714285714285714)

In [33]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [34]:
df.min()

cars      BMW
counts      1
dtype: object

In [35]:
df.max()

cars      Volvo
counts        9
dtype: object

In [36]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [37]:
df.count()

cars      7
counts    7
dtype: int64

In [38]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [39]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford" ],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [40]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [41]:
df_missing.dropna(how="all")

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [43]:
df_missing.dropna(axis=1) #(subset=['counts'])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [44]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [53]:
# df = pd.read_csv("Titanic-Dataset.csv")

# df.head(100)
df = pd.read_excel("test.xlsx")
df.tail()

 #df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [52]:
df.to_excel("test.xlsx")

In [54]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [55]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']